### ISSUE TITLE
树莓派3b无法连接wifi

### ISSUE THREAD

**Issue by HiedanoAkyuu** [musistudio/wukong-robot-install-script#1]
在执行完sudo wget http://wukong-install.oss-cn-hangzhou.aliyuncs.com/changeSource.sh && sudo chmod 777 changeSource.sh &&./changeSource.sh
命令重启后，树莓派无法找到wifi接口，网上找了不少方法也未能修复

**Comment by HiedanoAkyuu** [comment]
每次重烧树莓派官方系统执行完这条命令后wifi都不可用

**Comment by musistudio** [comment]
使用```ifconfig```看一下网卡信息

**Comment by HiedanoAkyuu** [comment]
ifconfig 没看到无线网卡的信息

**Comment by musistudio** [comment]
除了换源以外有没有进行过其他的操作？如果没有的话提供一下你使用的系统我看看能不能复现

**Comment by HiedanoAkyuu** [comment]
我之前一直用的16版系统，后来换18版已经没问题了，谢谢博主的回复
