### ISSUE TITLE
换源脚本不适用所有的系统，可以注明下

### ISSUE THREAD

**Issue by tmsdy** [musistudio/wukong-robot-install-script#14]
我用的是官方的： 2020-02-13-raspbian-buster-full.zip

> 
> root@raspberrypi:~/wukong-robot# cat /etc/debian_version
> 10.3
> root@raspberrypi:~/wukong-robot#  cat /etc/apt/sources.list
> deb http://mirrors.ustc.edu.cn/raspbian/raspbian/ stretch main contrib non-free rpi
> 

用了你换源脚本后装pulseaudio报错：

> root@raspberrypi:~/wukong-robot# apt-get install pulseaudio
> 正在读取软件包列表... 完成
> 正在分析软件包的依赖关系树       
> 正在读取状态信息... 完成       
> 有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
> 因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
> 包尚未被创建或是它们已被从新到(Incoming)目录移出。
> 下列信息可能会对解决问题有所帮助：
> 
> 下列软件包有未满足的依赖关系：
>  pulseaudio : 依赖: libpulse0 (= 10.0-1+deb9u1) 但是 12.2-4+deb10u1 正要被安装
>               依赖: pulseaudio-utils 但是它将不会被安装
> E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。

换源里面的stretch改为buster就可以安装了

[](https://i.loli.net/2020/04/12/fClU5IaLQ8KqdZy.png)

**Comment by musistudio** [comment]
感谢反馈，晚一点我更新一下

**Comment by musistudio** [comment]
已更新换源脚本，适配最新版。
关闭此issue
