### ISSUE TITLE
仓库比较老了，建议切官方gitee镜像源

### ISSUE THREAD

**Issue by wzpan** [musistudio/wukong-robot-install-script#21]
阿白啊，一键脚本用的阿里云镜像一看还是三年前的项目，经常有开发者跑过来问问题。

求将镜像站点更换为我另一个备用镜像源：https://gitee.com/wzpan/wukong-robot.git

**Comment by musistudio** [comment]
已经换好了

**Comment by musistudio** [comment]
> 阿白啊，一键脚本用的阿里云镜像一看还是三年前的项目，经常有开发者跑过来问问题。
> 
> 求将镜像站点更换为我另一个备用镜像源：https://gitee.com/wzpan/wukong-robot.git

另外之前的版本需要安装snowboy我看你的gitee上没有我就在我的账号下同步了一份
