### ISSUE TITLE
运行pulseaudio异常

### ISSUE THREAD

**Issue by YvanYangi** [musistudio/wukong-robot-install-script#8]
windows环境是mac下开的VMware。

![image](https://user-images.githubusercontent.com/42790947/61843372-ea10a980-aecd-11e9-8665-123e4ffea0c7.png)

**Comment by musistudio** [comment]
你这是mac上用Windows虚拟机再用wsl系统？

**Comment by YvanYangi** [comment]
是的

**Comment by musistudio** [comment]
请尝试使用64位操作系统
