### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by peter880805** [musistudio/wukong-robot-install-script#9]
![1081580341](https://user-images.githubusercontent.com/10109570/63825926-3d738d00-c98f-11e9-8e9b-5b3db4bf1ce4.jpg)

**Comment by peter880805** [comment]
win10 子系统下运行pulseaudio.exe 失败

**Comment by musistudio** [comment]
看报错信息你是不是已经运行过了？


------------------------------------------------------------------
发件人：peter880805 <notifications@github.com>
发送时间：2019年8月28日(星期三) 12:28
收件人：musistudio/wukong-robot-install-script <wukong-robot-install-script@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[musistudio/wukong-robot-install-script] 您好 (#9)

[1081580341]

**Comment by peter880805** [comment]
如何查看是否成功运行过

**Comment by peter880805** [comment]
> 看报错信息你是不是已经运行过了？
> […](#)
> ------------------------------------------------------------------ 发件人：peter880805 <notifications@github.com> 发送时间：2019年8月28日(星期三) 12:28 收件人：musistudio/wukong-robot-install-script <wukong-robot-install-script@noreply.github.com> 抄　送：Subscribed <subscribed@noreply.github.com> 主　题：[musistudio/wukong-robot-install-script] 您好 (#9) [1081580341] — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

如何查验是否成功安装了pulseaudio

**Comment by musistudio** [comment]
> > 看报错信息你是不是已经运行过了？
> > […](#)
> > ------------------------------------------------------------------ 发件人：peter880805 [notifications@github.com](mailto:notifications@github.com) 发送时间：2019年8月28日(星期三) 12:28 收件人：musistudio/wukong-robot-install-script [wukong-robot-install-script@noreply.github.com](mailto:wukong-robot-install-script@noreply.github.com) 抄　送：Subscribed [subscribed@noreply.github.com](mailto:subscribed@noreply.github.com) 主　题：[musistudio/wukong-robot-install-script] 您好 (#9) [1081580341] — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 如何查验是否成功安装了pulseaudio

在子系统中播放音频如果有声音就成功了

**Comment by peter880805** [comment]
![image](https://user-images.githubusercontent.com/10109570/63832071-9d276380-c9a2-11e9-89ec-49bb4ef07741.png)

**Comment by peter880805** [comment]
> > > 看报错信息你是不是已经运行过了？
> > > […](#)
> > > ------------------------------------------------------------------ 发件人：peter880805 [notifications@github.com](mailto:notifications@github.com) 发送时间：2019年8月28日(星期三) 12:28 收件人：musistudio/wukong-robot-install-script [wukong-robot-install-script@noreply.github.com](mailto:wukong-robot-install-script@noreply.github.com) 抄　送：Subscribed [subscribed@noreply.github.com](mailto:subscribed@noreply.github.com) 主　题：[musistudio/wukong-robot-install-script] 您好 (#9) [1081580341] — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > 
> > 如何查验是否成功安装了pulseaudio
> 
> 在子系统中播放音频如果有声音就成功了

没有检测到声卡？

**Comment by peter880805** [comment]
![QQ截图20190828145853](https://user-images.githubusercontent.com/10109570/63832936-694d3d80-c9a4-11e9-9145-2830dba6536f.png)
我刚刚重启电脑后，现在bug是这个？
